// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Company = sequelize.define('company', {
    companyName: {
      type: DataTypes.STRING,
      field: 'CompanyName',
    },
    companyAdress: {
      type: DataTypes.STRING,
      field: 'CompanyAdress',
    },
    createdAt: {
      type: DataTypes.DATEONLY,
      field: 'createdAt',
    },
  }, {
    tableName: 'Company',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Company.associate = (models) => {
    Company.hasMany(models.user, {
      foreignKey: {
        name: 'companyIdKey',
        field: 'CompanyId',
      },
      as: 'companyUsers',
    });
    Company.hasMany(models.session, {
      foreignKey: {
        name: 'companyIdKey',
        field: 'companyId',
      },
      as: 'companySessions',
    });
  };

  return Company;
};
