// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Show = sequelize.define('show', {
    showType: {
      type: DataTypes.STRING,
    },
    isDownloadable: {
      type: DataTypes.BOOLEAN,
    },
  }, {
    tableName: 'Show',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Show.associate = (models) => {
    Show.hasMany(models.session, {
      foreignKey: {
        name: 'showIdKey',
        field: 'showId',
      },
      as: 'showSessions',
    });
  };

  return Show;
};
